# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "equivalent-xml"
gem "fileutils"
gem "haml"
gem "json"
gem "nokogiri"
gem "open3"
gem "rdf"
gem "rerun"
gem "rest-client"
gem "sinatra"
gem "sinatra-partial"
gem "sparql"
gem "uuidtools"
gem "thin"
