# frozen_string_literal: true

source "https://rubygems.org"

gem 'rest-client'
gem 'json'
gem 'jwt'
gem 'addressable'
gem 'digest'
gem 'ffi'
gem 'sinatra'
gem 'puma'
gem "nokogiri"

gem "linkeddata", "~> 3.3"
