#+ summary: the scientific name of the species, and its endangerment status (Vulnerable, Endangered, Critically endangered)
#+ tags:
#+   - IUCN_categories
#+ endpoint_in_url: False



PREFIX fao: <https://w3id.org/fao-ipgr/multi-passport-descriptor.owl#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
PREFIX iucn: <http://iucn.org/terms/>
SELECT DISTINCT ?plant_scientificName  ?IUCN_endangerment_category
WHERE {
  ?taxon dwc:scientificName ?plant_scientificName .
  ?taxon iucn:threatStatus ?IUCN_endangerment_category
  FILTER(
    ?IUCN_endangerment_category = "http://rs.gbif.org/vocabulary/iucn/threat_status/VU" || 
    ?IUCN_endangerment_category = "http://rs.gbif.org/vocabulary/iucn/threat_status/EN" || 
    ?IUCN_endangerment_category = "http://rs.gbif.org/vocabulary/iucn/threat_status/CR"
  ).
}
