# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in fsp_harvester.gemspec
gemspec
ruby "3.3.0"

gem "cgi", "~> 0.4.1"
gem "compass"
gem "csv"
gem "fileutils", "~>1.5.0"
gem "json", "~> 2.7.1"
gem "json-canonicalization", "~> 1.0.0"
gem "linkeddata"
gem "openapi3_parser", "~> 0.9.2"
gem "rake", "~> 13.0"
gem "rest-client", "~>2.1.0"
gem "rspec", "~> 3.11"
gem "rubocop", "~> 1.7"
gem "ruby-debug-ide"
gem "securerandom"
gem "shotgun"
gem "sinatra", "~> 2.2"
gem "sinatra-cross_origin"
gem "swagger-blocks", "~> 3.0.0"
gem "tempfile"
gem "thin"
gem "tux"
gem "uri", "~>0.12.2"
gem "pony", "~>1.13.1"
gem "xml-simple", "~>1.1.8"


gem "require_all", "~> 3.0"
