version: "3"
services:


  flair-box-daemon: 
    image: markw/flair-box-daemon:0.0.1   
    container_name: flair-box-daemon
    environment:
      GraphDB_User: ${GraphDB_User}
      GraphDB_Pass: ${GraphDB_Pass}
      baseURI: ${baseURI}
    depends_on:
      - yarrrml-rdfizer
    ports:
      - 4567:4567
    volumes:
        - ./data:/data
    networks:
      - default
      - graphdb_net 
        
 
  yarrrml-rdfizer:
    image: markw/yarrrml-rml-ejp:0.0.3
    container_name: yarrrml-rdfizer
    hostname: yarrrml-rdfizer
    environment:
      # (nquads (default), trig, trix, jsonld, hdt, turtle)
      - SERIALIZATION=nquads
#    ports:
#      - "4567:4567"
    volumes:
      - ./data:/mnt/data
    networks:
      - default
      - graphdb_net 
networks:
  graphdb_net:
