version: "3"
services:


  # FAIR Data Point client	
  fdp_client:
    image: fairdata/fairdatapoint-client:1.16.3
    hostname: fdpclient
    restart: always
    environment:
      FDP_HOST: fdp
    volumes:
      - ./fdp/variables.scss:/src/scss/custom/_variables.scss:ro
      - ./fdp/assets:/usr/share/nginx/html/assets:ro
      - ./fdp/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    depends_on:
      - fdp
    ports:
      - {FDP_PORT}:80
    networks:
      - {PREFIX}-default

  graphdb:
    image: ontotext/graphdb:10.1.2
    restart: always
    hostname: graphdb
    ports:
      - {GDB_PORT}:7200
    volumes:
      - {PREFIX}-graphdb:/opt/graphdb/home
    networks:
      - {PREFIX}-default

  fdp:
    image: fairdata/fairdatapoint:1.16.2
    restart: always
    hostname: fdp
    volumes:
      - ./fdp/application-{PREFIX}.yml:/fdp/application.yml:ro
    depends_on:
      - mongo
      - graphdb
    networks:
      - {PREFIX}-default
        
      
  # Mongo for FDP server    
  mongo:
    image: mongo:4.2.3
    hostname: mongo
    restart: always
    volumes:
      - {PREFIX}-mongo-data:/data/db
      - {PREFIX}-mongo-init:/docker-entrypoint-initdb.d/
    networks:
      - {PREFIX}-default

  flair-box-daemon: 
    image: markw/flair-box-daemon:0.0.6
    environment:
      GraphDB_User: ${GraphDB_User}
      GraphDB_Pass: ${GraphDB_Pass}
      baseURI: ${baseURI}
      GRAPHDB_REPONAME: ${GRAPHDB_REPONAME}
    depends_on:
      - yarrrml-rdfizer
    ports:
      - 127.0.0.1:{RDF_TRIGGER}:4567
    volumes:
        - ./data:/data
    networks:
      - {PREFIX}-default


  yarrrml-rdfizer:
    image: markw/yarrrml-rml-ejp:0.0.3
    hostname: yarrrml-rdfizer
    environment:
      # (nquads (default), trig, trix, jsonld, hdt, turtle)
      - SERIALIZATION=nquads
    volumes:
      - ./data:/mnt/data
    networks:
      - {PREFIX}-default


volumes:
  {PREFIX}-graphdb:
    external: true
  {PREFIX}-mongo-data:
    external: true
  {PREFIX}-mongo-init:
    external: true
  {PREFIX}-fdp-server:
    external: true

networks:
  {PREFIX}-default:
