Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
  
Metrics/ParameterLists:
  Enabled: false

Style/Documentation:  # Example for a Style cop
  Enabled: false

Style/ClassVars:  # Example for a Style cop
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false