# frozen_string_literal: false

source 'https://rubygems.org'

gemspec
ruby '~> 3.2'
gem 'bcrypt'
# gem 'debase', git: 'https://github.com/ruby-debug/debase.git', tag: 'v0.2.5.beta2'
gem 'csv'
gem 'fileutils'
gem 'json'
gem 'json-canonicalization'

gem 'parseconfig'
gem 'rake'
gem 'require_all'
gem 'securerandom'
gem 'tempfile'
gem 'xml-simple'

# group :test do
#   gem 'capybara'
#   gem 'rack-test'
#   gem 'rspec'
#   gem 'rspec-core'
#   gem 'rspec-openapi'
# end


group :development do
  gem 'capybara'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-core'
  gem 'rspec-openapi'
  gem 'webmock'
  gem 'rubocop'
  gem 'guard'
  gem 'shotgun' 
  gem 'pry'
end



# gem "omniauth", "~> 1.1"

# gem "omniauth-openid-connect", "~> 0.2.3"

gem 'jwt'

gem 'sinatra-respond_to'

gem 'nokogiri', '~> 1.16'

gem 'linkeddata', '~> 3.2'

gem "erb", "~> 4.0"

gem "sinatra", "~> 2.2"

gem "rdf-raptor", "~> 3.1"

gem "cgi", "~> 0.5.1"

gem "sinatra-cross_origin", "~> 0.4.0"

gem "rest-client", "~> 2.1"

gem "openapi3_parser", "~> 0.10.0"

gem "swagger-blocks", "~> 3.0"

gem "metainspector", "~> 5.15"

gem "thin", "~> 1.8"

gem 'connection_pool', '~> 2.5'