# frozen_string_literal: false

source "https://rubygems.org"

gemspec
ruby "~> 3.0"
# gem 'activerecord', '~> 7', '>= 7', require: 'active_record'
gem "bcrypt"
gem "debase", git: "https://github.com/ruby-debug/debase.git", tag: "v0.2.5.beta2"
gem "linkeddata", "~> 3.2.0"
gem "metainspector", "~> 5-11-2"
gem "parseconfig", "~>1.1.2"
gem "pry"
gem "rake", "~> 13.0"
gem "rdf-raptor", "~> 3.1.0"
gem "require_all"
gem "rest-client", "~>2.1.0"
gem "rspec", "~> 3.11.0"
gem "rubocop"
gem "ruby-debug-ide"
gem "shotgun"
gem "sinatra", "~> 2.2"
# gem 'sinatra-json'
# gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem "json", "~> 2.7.1"
gem "json-canonicalization", "~> 1.0.0"
gem "sinatra-cross_origin"
gem "swagger-blocks", "~> 3.0.0"
gem "thin"
gem "tux"
gem "uri", "~>0.12.2"
gem "xml-simple", "~>1.1.8"
gem "fileutils", "~>1.5.0"
gem 'openapi3_parser', '~> 0.9.2'
gem "cgi", "~> 0.4.1"

group :test do
  gem "capybara"
  gem "rack-test"
  # gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end
