openapi: 3.0.3
info:
  title: TOGOWS Sequence Lookup Service
  description: |-
    TOGOWS Sequence Lookup Service
  termsOfService: http://swagger.io/terms/
  contact:
    email: mark.wilkinson@upm.es
  license:
    name: MIT 
    url: http://purl.org/NET/rdflicense/MIT1.0.ttl
  version: 1.0.0
externalDocs:
  description: Find out more about TOGO Web Services
  url: http://togows.dbcls.jp/
servers:
  - url: http://togows.org/
tags:
  - name: sequence
    description: Retrieve sequences from the ENA archive
    externalDocs:
      description: Find out more about ENA
      url: https://www.ebi.ac.uk/ena/browser/home
paths:
  /entry/ebi-ena/{sid}/seq.json:
    get:
      tags:
        - sequence
      summary: Retrieve Sequence by ENA identifier
      description: Returns sequences for that identifier
      operationId: getSeqById
      parameters:
        - name: sid
          in: path
          description: ID of sequence to return
          required: true
          schema:
            type: string
            example: AAP46064

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Seq'  
        '400':
          description: Invalid ID supplied
        '404':
          description: Sequence not found

components:
  schemas:
    Seq:
      type: object
