openapi: 3.0.3
info:
  title: FLAIR-GG Wrapped Servies
  description: |-
    Services that needed to be "wrapped" to be included in the FLAIR-GG network
  termsOfService: http://swagger.io/terms/
  contact:
    email: mark.wilkinson@upm.es
  license:
    name: MIT 
    url: http://purl.org/NET/rdflicense/MIT1.0.ttl
  version: 1.0.0
externalDocs:
  description: Driada
  url: https://www.conservacionvegetal.org/driada/
servers:
  - url: https://vp.bgv.cbgp.upm.es
tags:
  - name: species_lookup
    description: lookup species in DIADRA index
paths:
  /wrapped_services/driada/lookup:
    get:
      tags:
        - species
      summary: Retrieve the legal protection status for a species, as well as taxonomic information.
      description: Check in the Spanish Catalog of Threatened species, the List of Wild Species under Special Protection Regime and the regional spanish catalogs if a species has legal protection in Spain.
      operationId: getDiadraBySpecies
      parameters:
        - name: species
          in: query
          description: species to lookup
          required: true
          schema:
            type: string
            example: Abies pinsapo
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Species'  
        '400':
          description: Invalid species supplied
        '404':
          description: Sequence not found

components:
  schemas:
    Species:
      type: object
