version: "3"
services:
  
  yarrml-rdfizer: 
    image: markw/yarrrml-rdfizer-flair:0.0.91

    environment:
      - SERIALIZATION=nquads
    ports:
      - "4567:4567"
    volumes:
      - ./data:/mnt/data
