version: "3"
services:

  
  yarrml-rdfizer: 
#    image: markw/yarrrml-rml-ejp:0.0.2
    image: yarrrml
    environment:
      # (nquads (default), trig, trix, jsonld, hdt, turtle)
      - SERIALIZATION=nquads
    ports:
      - "4567:4567"
    volumes:
      - ./data:/mnt/data
